### ISSUE TITLE
System Insights Button Is Missing From Server View

### ISSUE THREAD

**Issue by BinaryWizard904** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#153]
**Gateway Version**: 1.3.2111.01001
**Extension Version**: System Insights: 2.7.0
**Version of Windows Server on mytestserver**: Windows Server 2022 Standard Evaluation (Build 10.0.20348.558)

**To Reproduce**
1. Add a Windows Server 2022 server to Windows Admin Center
2. Click on the server to open it's overview.
3. Notice that the "System Insights" button is not available.
4. Replace "overview" in the URL with "system-insights" and navigate to it. e.g.:
     `https://localhost:6516/servermanager/connections/server/mytestserver/tools/system-insights`
5. Observe that System Insights is installed, supported, and functions as expected; aside from the button missing. 

**Expected behavior**
"System Insights" should be listed under "Tools" for servers it is supported on.

**Screenshots & Additional context**
![Screenshot - 4_6_2022 , 10_38_54 AM](https://user-images.githubusercontent.com/62070150/162016165-475a2054-d660-4b47-84b8-89b1dbd8f3c3.png)

Troubleshooting steps I have taken so far:

- Managing the server using another user.
- Opening Windows Admin Center in Microsoft Edge and Mozilla Firefox.
- Reinstalling the System Insights extension.
- Reinstalling Windows Admin Center using a fresh installer downloaded from Microsoft.

**Comment by trungtran-msft** [comment]
@BinaryWizard904 I believe this has been fixed in our latest public preview release. Can you please try it out and see? 
https://techcommunity.microsoft.com/t5/windows-admin-center-blog/windows-admin-center-version-2110-2-is-now-in-public-preview/ba-p/3263839

**Comment by trungtran-msft** [comment]
I'm so sorry to hear that, I contacted the team who owns this feature but they have not been able to reproduce the issue and neither can I. Can you check the console on your browser to see if there are any errors in the calls?

**Comment by BinaryWizard904** [comment]
@trungtran-msft There are no error messages when loaded in Microsoft Edge, but in Firefox I get a few `msft.sme.server-manager -- appErrorHandler` errors.  Though that might be related to how the graphs for CPU and Memory don't work in Firefox than anything related to system-insights.  See: [console-export-2022-4-15_13-33-40.txt](https://github.com/MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback/files/8497494/console-export-2022-4-15_13-33-40.txt)

**Comment by BinaryWizard904** [comment]
I just created a new Windows Server 2022 VM based on a Full ISO instead of the Evaluation version.  Guess what?  The System Insights button appears when managing _that_ VM.  It is still missing for the VM with Windows Server 2022 Standard Evaluation.  Could this issue be related to the Edition of Windows Server being managed?
